// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chaos-io/chaos/infra/tracer (interfaces: Span)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSpan is a mock of Span interface.
type MockSpan struct {
	ctrl     *gomock.Controller
	recorder *MockSpanMockRecorder
}

// MockSpanMockRecorder is the mock recorder for MockSpan.
type MockSpanMockRecorder struct {
	mock *MockSpan
}

// NewMockSpan creates a new mock instance.
func NewMockSpan(ctrl *gomock.Controller) *MockSpan {
	mock := &MockSpan{ctrl: ctrl}
	mock.recorder = &MockSpanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpan) EXPECT() *MockSpanMockRecorder {
	return m.recorder
}

// SetCallType mocks base method.
func (m *MockSpan) SetCallType(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCallType", arg0)
}

// SetCallType indicates an expected call of SetCallType.
func (mr *MockSpanMockRecorder) SetCallType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCallType", reflect.TypeOf((*MockSpan)(nil).SetCallType), arg0)
}
