// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chaos-io/chaos/infra/lock (interfaces: ILocker)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	lock "github.com/chaos-io/chaos/infra/lock"
	gomock "github.com/golang/mock/gomock"
)

// MockILocker is a mock of ILocker interface.
type MockILocker struct {
	ctrl     *gomock.Controller
	recorder *MockILockerMockRecorder
}

// MockILockerMockRecorder is the mock recorder for MockILocker.
type MockILockerMockRecorder struct {
	mock *MockILocker
}

// NewMockILocker creates a new mock instance.
func NewMockILocker(ctrl *gomock.Controller) *MockILocker {
	mock := &MockILocker{ctrl: ctrl}
	mock.recorder = &MockILockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILocker) EXPECT() *MockILockerMockRecorder {
	return m.recorder
}

// ExpireLockIn mocks base method.
func (m *MockILocker) ExpireLockIn(arg0 string, arg1 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireLockIn", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireLockIn indicates an expected call of ExpireLockIn.
func (mr *MockILockerMockRecorder) ExpireLockIn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireLockIn", reflect.TypeOf((*MockILocker)(nil).ExpireLockIn), arg0, arg1)
}

// Lock mocks base method.
func (m *MockILocker) Lock(arg0 context.Context, arg1 string, arg2 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockILockerMockRecorder) Lock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockILocker)(nil).Lock), arg0, arg1, arg2)
}

// LockBackoff mocks base method.
func (m *MockILocker) LockBackoff(arg0 context.Context, arg1 string, arg2, arg3 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBackoff", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockBackoff indicates an expected call of LockBackoff.
func (mr *MockILockerMockRecorder) LockBackoff(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBackoff", reflect.TypeOf((*MockILocker)(nil).LockBackoff), arg0, arg1, arg2, arg3)
}

// LockBackoffWithRenew mocks base method.
func (m *MockILocker) LockBackoffWithRenew(arg0 context.Context, arg1 string, arg2, arg3 time.Duration) (bool, context.Context, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBackoffWithRenew", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(context.Context)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LockBackoffWithRenew indicates an expected call of LockBackoffWithRenew.
func (mr *MockILockerMockRecorder) LockBackoffWithRenew(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBackoffWithRenew", reflect.TypeOf((*MockILocker)(nil).LockBackoffWithRenew), arg0, arg1, arg2, arg3)
}

// LockWithRenew mocks base method.
func (m *MockILocker) LockWithRenew(arg0 context.Context, arg1 string, arg2, arg3 time.Duration) (bool, context.Context, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockWithRenew", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(context.Context)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LockWithRenew indicates an expected call of LockWithRenew.
func (mr *MockILockerMockRecorder) LockWithRenew(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockWithRenew", reflect.TypeOf((*MockILocker)(nil).LockWithRenew), arg0, arg1, arg2, arg3)
}

// Unlock mocks base method.
func (m *MockILocker) Unlock(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockILockerMockRecorder) Unlock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockILocker)(nil).Unlock), arg0)
}

// WithHolder mocks base method.
func (m *MockILocker) WithHolder(arg0 string) lock.ILocker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithHolder", arg0)
	ret0, _ := ret[0].(lock.ILocker)
	return ret0
}

// WithHolder indicates an expected call of WithHolder.
func (mr *MockILockerMockRecorder) WithHolder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithHolder", reflect.TypeOf((*MockILocker)(nil).WithHolder), arg0)
}
