// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: hail.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whom string `protobuf:"bytes,1,opt,name=whom,proto3" json:"whom,omitempty"`
}

func (x *Hail) Reset() {
	*x = Hail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hail) ProtoMessage() {}

func (x *Hail) ProtoReflect() protoreflect.Message {
	mi := &file_hail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hail.ProtoReflect.Descriptor instead.
func (*Hail) Descriptor() ([]byte, []int) {
	return file_hail_proto_rawDescGZIP(), []int{0}
}

func (x *Hail) GetWhom() string {
	if x != nil {
		return x.Whom
	}
	return ""
}

type NotHail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NotHail) Reset() {
	*x = NotHail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotHail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotHail) ProtoMessage() {}

func (x *NotHail) ProtoReflect() protoreflect.Message {
	mi := &file_hail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotHail.ProtoReflect.Descriptor instead.
func (*NotHail) Descriptor() ([]byte, []int) {
	return file_hail_proto_rawDescGZIP(), []int{1}
}

func (x *NotHail) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_hail_proto protoreflect.FileDescriptor

var file_hail_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04,
	0x48, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x6f, 0x6d, 0x22, 0x72, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x48,
	0x61, 0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4e, 0x6f, 0x74, 0x48, 0x61, 0x69, 0x6c, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hail_proto_rawDescOnce sync.Once
	file_hail_proto_rawDescData = file_hail_proto_rawDesc
)

func file_hail_proto_rawDescGZIP() []byte {
	file_hail_proto_rawDescOnce.Do(func() {
		file_hail_proto_rawDescData = protoimpl.X.CompressGZIP(file_hail_proto_rawDescData)
	})
	return file_hail_proto_rawDescData
}

var file_hail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hail_proto_goTypes = []interface{}{
	(*Hail)(nil),    // 0: Hail
	(*NotHail)(nil), // 1: NotHail
	nil,             // 2: NotHail.FieldsEntry
}
var file_hail_proto_depIdxs = []int32{
	2, // 0: NotHail.fields:type_name -> NotHail.FieldsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hail_proto_init() }
func file_hail_proto_init() {
	if File_hail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotHail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hail_proto_goTypes,
		DependencyIndexes: file_hail_proto_depIdxs,
		MessageInfos:      file_hail_proto_msgTypes,
	}.Build()
	File_hail_proto = out.File
	file_hail_proto_rawDesc = nil
	file_hail_proto_goTypes = nil
	file_hail_proto_depIdxs = nil
}
